name: Orquestra Pipeline

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
    
        runs-on: ubuntu-latest

        steps:
        - name: Code checkout
          uses: actions/checkout@v4

        - name: .NET install
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9.0.x'

        - name: Dependencies restore
          run: dotnet restore

        - name: Application build
          run: dotnet build --no-restore --configuration Release